"""
Octa Intelligence — Document Processor
Extracts text from PDF, Word documents and URLs.
"""
import io
import requests
from config import MAX_TEXT_CHARS


def extract_from_pdf(file_bytes: bytes) -> tuple[str, int]:
    """Extract text from PDF bytes. Returns (text, page_count)."""
    try:
        import fitz  # PyMuPDF
        doc  = fitz.open(stream=file_bytes, filetype="pdf")
        pages= doc.page_count
        text = ""
        for page in doc:
            text += page.get_text()
        doc.close()
        return text.strip(), pages
    except Exception as e:
        return f"[PDF extraction error: {e}]", 0


def extract_from_docx(file_bytes: bytes) -> tuple[str, int]:
    """Extract text from Word .docx bytes. Returns (text, estimated_pages)."""
    try:
        from docx import Document
        doc   = Document(io.BytesIO(file_bytes))
        paras = [p.text for p in doc.paragraphs if p.text.strip()]
        text  = "\n".join(paras)
        # Rough page estimate: ~300 words per page
        words = len(text.split())
        pages = max(1, words // 300)
        return text.strip(), pages
    except Exception as e:
        return f"[DOCX extraction error: {e}]", 0


def extract_from_url(url: str, timeout: int = 30) -> tuple[str, int]:
    """Fetch and extract text from a URL. Returns (text, estimated_pages)."""
    try:
        headers = {"User-Agent": "Mozilla/5.0 (compatible; OctaBot/1.0)"}
        resp    = requests.get(url, headers=headers, timeout=timeout)
        resp.raise_for_status()

        content_type = resp.headers.get("content-type","")

        if "pdf" in content_type:
            return extract_from_pdf(resp.content)

        # HTML — strip tags
        from bs4 import BeautifulSoup
        soup  = BeautifulSoup(resp.text, "html.parser")
        # Remove scripts, styles, nav
        for tag in soup(["script","style","nav","header","footer","aside"]):
            tag.decompose()
        text  = soup.get_text(separator="\n")
        # Clean up whitespace
        lines = [l.strip() for l in text.splitlines() if l.strip()]
        text  = "\n".join(lines)
        words = len(text.split())
        pages = max(1, words // 300)
        return text.strip(), pages

    except Exception as e:
        return f"[URL extraction error: {e}]", 0


def prepare_text_for_storage(text: str) -> tuple[str, bool]:
    """
    Returns (stored_text, was_truncated).
    If text > MAX_TEXT_CHARS, truncate with a note.
    Full summary will be generated by Claude separately.
    """
    if len(text) <= MAX_TEXT_CHARS:
        return text, False
    truncated = text[:MAX_TEXT_CHARS]
    truncated += f"\n\n[... Document truncated at {MAX_TEXT_CHARS:,} characters. Full text available in original file.]"
    return truncated, True


def chunk_text(text: str, chunk_size: int = 400_000,
               overlap: int = 200) -> list[str]:
    """
    Split text into overlapping chunks for large document processing.
    Used when sending to Claude API.
    """
    if len(text) <= chunk_size:
        return [text]
    chunks = []
    start  = 0
    while start < len(text):
        end = min(start + chunk_size, len(text))
        chunks.append(text[start:end])
        start = end - overlap
    return chunks


def count_words(text: str) -> int:
    return len(text.split())


def estimate_tokens(text: str) -> int:
    """Rough estimate: 1 token ≈ 4 characters."""
    return len(text) // 4
